version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform *Network as Code* Meraki Model Module

  This module can be used to create a single YAML file including the full model and all templates being applied. This can be useful to run validations against the full model.

  ## Examples

  ```hcl
  {{ include "./examples/model_file/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false