version: ">= 0.14.0"

formatter: markdown table

content: |-
  # Terraform Network-as-Code Cisco Meraki Module

  A Terraform module to configure Cisco Meraki.

  ## Usage

  This module supports an inventory driven approach, where a complete Meraki configuration or parts of it are either modeled in one or more YAML files or natively using Terraform variables.

  ## Examples

  Configuring an organization administrator using YAML:

  #### `organization.yaml`

  ```yaml
  {{ include "./examples/administrator/organizations_admins.yaml" }}
  ```

  #### `main.tf`

  ```hcl
  {{ include "./examples/administrator/main.tf" }}
  ```

  {{ .Requirements }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
  {{ .Modules }}
output:
  file: README.md
  mode: replace

sort:
  enabled: true
  by: required
